apiVersion: v1
kind: Service
metadata:
  name: perf-aidashboard-staging-service
  namespace: perf-aidashboard
  labels:
    app: perf-aidashboard-staging
    app.kubernetes.io/name: perf-aidashboard-staging
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: perf-aidashboard-staging
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      name: http
